DELIMITER $$
  CREATE OR REPLACE FUNCTION GET_CURRENT_REGYEAR(STDID VARCHAR(10))
  RETURNS VARCHAR(50)
  
  BEGIN 
	DECLARE REGYEAR VARCHAR(20);
	SELECT YEAR_NAME FROM studentregistrations
	WHERE STUDENT_ID = STDID
	ORDER BY REGISTRATION_ID DESC
	LIMIT 1
	INTO REGYEAR;
	
	RETURN REGYEAR;
  END $$

DELIMITER ;