DELIMITER $$
    CREATE OR REPLACE FUNCTION GET_CURRENT_SEMESTERID(STDID VARCHAR(20))
    RETURNS VARCHAR(20)
    
    BEGIN
	DECLARE DEPID VARCHAR(20);
	SELECT SEMESTER_ID FROM studentregistrations
	WHERE STUDENT_ID=STDID
	ORDER BY REGISTRATION_ID DESC
	LIMIT 1
	
	INTO DEPID;
	
	RETURN DEPID;
    END $$
DELIMITER ;