DELIMITER $$
    CREATE OR REPLACE FUNCTION GET_CURRENT_REGDATE(STDID VARCHAR(20))
    RETURNS VARCHAR(20)
    
    BEGIN
	DECLARE REGDATE VARCHAR(20);
	SELECT REGISTRATION_DATE FROM studentregistrations
	WHERE STUDENT_ID=STDID
	ORDER BY REGISTRATION_ID DESC
	LIMIT 1
	INTO REGDATE;
	
	RETURN REGDATE;
    END $$
DELIMITER ;