DELIMITER $$

CREATE OR REPLACE
    FUNCTION GET_CURRENT_DEPARTMENT(stdid VARCHAR(20))
    RETURNS VARCHAR(20)
    
    BEGIN
	DECLARE DPTNAME VARCHAR(100);
	
	SELECT GET_DEPARTMENT_NAME(DEPARTMENT_ID) FROM studentregistrations 
		WHERE student_id=stdid 
		ORDER BY registration_id DESC 
		LIMIT 1 
		INTO DPTNAME;
		
	RETURN DPTNAME;
    END$$

DELIMITER ;